# Generated by Django 4.2.7 on 2025-11-15 08:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('business_id', models.CharField(default='default_business', max_length=100)),
                ('title', models.CharField(max_length=500)),
                ('subtitle', models.CharField(blank=True, max_length=500, null=True)),
                ('content', models.TextField()),
                ('cover_image_url', models.URLField(blank=True, null=True)),
                ('category', models.CharField(choices=[('Technology', 'Technology'), ('Science', 'Science'), ('Business', 'Business'), ('Health', 'Health'), ('Education', 'Education'), ('Other', 'Other')], default='Other', max_length=50)),
                ('author_name', models.CharField(max_length=200)),
                ('author_id', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_review', 'Pending Review'), ('published', 'Published'), ('rejected', 'Rejected')], default='draft', max_length=20)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.CharField(blank=True, max_length=100, null=True)),
                ('approved_by_name', models.CharField(blank=True, max_length=200, null=True)),
                ('rejected_by', models.CharField(blank=True, max_length=100, null=True)),
                ('rejected_by_name', models.CharField(blank=True, max_length=200, null=True)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'articles',
                'ordering': ['-created_at'],
            },
        ),
    ]
